if(!require('utils')) install.packages("utils", repos = 'http://cran.us.r-project.org'); library('utils')
if(!require('glue')) install.packages("glue", repos = 'http://cran.us.r-project.org'); library('glue')
if(!require('stats')) install.packages("stats", repos = 'http://cran.us.r-project.org'); library('stats')
if(!require('tidyverse')) install.packages("tidyverse", repos = 'http://cran.us.r-project.org'); library('tidyverse')
if(!require('dplyr')) install.packages("", repos = 'http://cran.us.r-project.org'); library('dplyr')
if(!require('corrplot')) install.packages("corrplot", repos = 'http://cran.us.r-project.org'); library('corrplot')
if(!require('rcompanion')) install.packages("rcompanion", repos = 'http://cran.us.r-project.org'); library('rcompanion')
if(!require('here')) install.packages("here", repos = 'http://cran.us.r-project.org'); library('here')
if(!require('psych')) install.packages("psych", repos = 'http://cran.us.r-project.org'); library('psych')
if(!require('boot')) install.packages("boot", repos = 'http://cran.us.r-project.org'); library('boot')
if(!require('magrittr')) install.packages("magrittr", repos = 'http://cran.us.r-project.org'); library('magrittr')
if(!require('lubridate')) install.packages("lubridate", repos = 'http://cran.us.r-project.org'); library('lubridate')
if(!require('gridExtra')) install.packages("gridExtra", repos = 'http://cran.us.r-project.org'); library('gridExtra')
if(!require('fastDummies')) install.packages("fastDummies", repos = 'http://cran.us.r-project.org'); library('fastDummies')
if(!require('xgboost')) install.packages("xgboost", repos = 'http://cran.us.r-project.org'); library('xgboost')
if(!require('caret')) install.packages("caret", repos = 'http://cran.us.r-project.org'); library('caret')
if(!require('ppcor')) install.packages("ppcor", repos = 'http://cran.us.r-project.org'); library('ppcor')
if(!require('stringi')) install.packages("stringi", repos = 'http://cran.us.r-project.org'); library('stringi')
if(!require('scales')) install.packages("scales", repos = 'http://cran.us.r-project.org'); library('scales')
if(!require('viridis')) install.packages("viridis", repos = 'http://cran.us.r-project.org'); library('viridis')


source(here::here("function_bootstrap_script.R"))
